/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;


import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        readBitMap();
        System.out.println(new App().getGreeting());

    }
        public static void readBitMap() {

           BitMap test = new BitMap("src/main/resources/mario.bmp", "src/main/resources/output.bmp");
            test.negativeRGB();
        }

}
