/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;


import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        String inputPath = "src/main/resources/" + args[0] + ".bmp";
        String outputPath = "src/main/resources/" + args[1] + ".bmp";
        String transformationType = args[2].toLowerCase();

        Bitmap test = new Bitmap(inputPath, outputPath);

       switch (transformationType) {
            case "invert" :
                test.negativeRGBTransformation();
                break;
            case "grayscale" :
                test.grayscaleTransformation();
                break;
            case "mirror" :
                test.mirroredTransformation();
                break;
            default :
                System.out.println("IYour transformation request is denied. Please pick: 'invert', 'greyscale', 'mirror'");
        }

    }


}
